char *list[] = {
    "/view/ccc/cccForStudent.md",
    "/view/ccc/cccForProfessor.md",
    "/view/ccc/cccForProgrammer.md",
    "/view/ccc/cccForCompany.md",
    "/view/ccc/course.md",
    "/view/nand2tetris/chapter1.md",
    "/view/nand2tetris/chapter2.md",
    "/view/nand2tetris/chapter3.md",
    "/view/nand2tetris/chapter4.md",
    "/view/nand2tetris/chapter5.md",
    "/view/nand2tetris/chapter6.md",
    "/view/nand2tetris/chapter7.md",
    "/view/nand2tetris/chapter8.md",
    "/view/nand2tetris/chapter9.md",
    "/view/nand2tetris/chapter10.md",
    "/view/nand2tetris/chapter11.md",
    "/view/nand2tetris/chapter12.md",
    "/view/jsh/chapter1.md",
    "/view/jsh/chapter2.md",
    "/view/jsh/chapter3.md",
    "/view/jsh/chapter4.md",
    "/view/jsh/chapter5.md",
    "/view/jsh/chapter6.md",
    "/view/jsh/chapter7.md",
    "/view/jsh/chapter8.md",
    "/view/jsh/chapter9.md",
    "/view/jsh/chapter10.md",
    "/view/jsh/chapter11.md",
};

#define LIST_SIZE (sizeof(list)/sizeof(char*))
