@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(-msep-data patches) for ARM/elf
	.file	"StackMain.c"
.gcc2_compiled.:
	.section .rodata
	.align	2
.LC0:
	.ascii	"x=%d\012\000"
.text
	.align	2
	.global	main
	.type	 main,function
main:
	@ args = 0, pretend = 0, frame = 4
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #4
	bl	__gccmain
	mov	r0, #3
	bl	push
	bl	pop
	mov	r3, r0
	str	r3, [fp, #-16]
	ldr	r0, .L3
	ldr	r1, [fp, #-16]
	bl	printf
	mov	r0, #0
	b	.L2
.L4:
	.align	2
.L3:
	.word	.LC0
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 main,.Lfe1-main
