@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(-msep-data patches) for ARM/elf
	.file	"StackType.c"
.gcc2_compiled.:
	.global	top
.data
	.align	2
	.type	 top,object
	.size	 top,4
top:
	.word	0
	.comm	stack, 400	@ 400
