// 參考 https://github.com/cccbook/bottomupcs/wiki/08-bprocess
// windows 中請在 MSYS2 裏執行！

int main(void) {
	char *foo = (char*)0x12345;
	*foo = 'a';

	return 0;
}

/* 執行結果 (在 MSYS2 中)

user@DESKTOP-96FRN6B MINGW64 /d/ccc/book/sp/code/c/14-memory
$ ./coredump

沒有發生錯誤

但 Linux 中應該預期如下的錯誤：

$ gcc -Wall -g -o coredump coredump.c

$ ./coredump
Segmentation fault (core dumped)

$ file ./core
./core: ELF 32-bit LSB core file Intel 80386, version 1 (SYSV), SVR4-style, from './coredump'

$ gdb ./coredump
...
(gdb) core core
[New LWP 31614]
Core was generated by `./coredump'.
Program terminated with signal 11, Segmentation fault.
#0  0x080483c4 in main () at coredump.c:3
3		*foo = 'a';
(gdb)

*/